"""
UrbanSense AI — Canonical Event Contract
=========================================
SOURCE OF TRUTH: URBANSENSE_FINAL_MASTER_IMPLEMENTATION_PLAN.md (R4)

The CanonicalEvent is the primary inter-module message.
Edge produces it. Backend ingests, validates, and enriches it.

OWNERSHIP RULES:
- Edge-owned fields: observation_id, opportunity_id, event_timestamp,
  location, edge_road_segment_hint, detector_confidence,
  observation_quality, gps_quality, model_*, priority, trace_id,
  producer_sequence, payload_hash, bus_id, device_id, camera_id
- Backend-owned fields (NOT to be set by Edge):
  ingestion_timestamp, matched_road_segment_id,
  map_match_confidence, map_match_status, event_id (generated by backend after idempotency check)
- edge_road_segment_hint is ADVISORY. Backend map-match is AUTHORITATIVE.

SEMANTIC NOTES:
- event_timestamp = time the event occurred (historical semantics).
- ingestion_timestamp = time the backend received it (operational metadata).
- detector_confidence, observation_quality, gps_quality are SEPARATE fields.
  Never merge into a single "confidence".

DATA SHAPES ONLY. No business logic here.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict
import uuid


class MapMatchStatus(str, Enum):
    MATCHED = "MATCHED"
    AMBIGUOUS = "AMBIGUOUS"
    UNMATCHED = "UNMATCHED"
    PENDING = "PENDING"   # Backend has not yet performed map-match


class EventPriority(str, Enum):
    P0 = "P0"   # Incident/life-safety — publish instantly
    P1 = "P1"   # Significant defect
    P2 = "P2"   # Standard observation
    P3 = "P3"   # Low-priority / batched


class Location(BaseModel):
    """WGS-84 point location from Edge GNSS."""
    latitude: float = Field(ge=-90.0, le=90.0)
    longitude: float = Field(ge=-180.0, le=180.0)
    altitude_m: Optional[float] = Field(default=None)
    accuracy_m: Optional[float] = Field(default=None, description="Horizontal accuracy estimate.")
    heading_deg: Optional[float] = Field(default=None, description="Vehicle heading in degrees.")


class CanonicalEvent(BaseModel):
    """
    The primary Edge-to-Backend event message.

    Fields labelled [BACKEND-OWNED] must NOT be populated by the Edge.
    The Edge may populate edge_road_segment_hint as advisory only.
    """

    # --- Identity ---
    event_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Stable unique identifier. Used for idempotency by backend.",
    )
    schema_version: str = Field(
        default="1.0",
        description="Contract schema version for forward compatibility.",
    )

    # --- Producer context ---
    bus_id: str
    device_id: str
    camera_id: str

    # --- Time ---
    event_timestamp: datetime = Field(
        description=(
            "UTC time the event occurred (from Edge clock). "
            "This is the HISTORICAL timestamp — use for event semantics. "
            "Do NOT use ingestion_timestamp for historical queries."
        )
    )
    ingestion_timestamp: Optional[datetime] = Field(
        default=None,
        description=(
            "[BACKEND-OWNED] Time the backend received the event. "
            "This is operational metadata only. Set by backend, not Edge."
        ),
    )

    # --- Location (Edge-produced) ---
    location: Location = Field(description="WGS-84 position from Edge GNSS at event time.")

    # --- Map matching (BACKEND-OWNED) ---
    edge_road_segment_hint: Optional[str] = Field(
        default=None,
        description=(
            "ADVISORY: Edge's best guess at road segment from its GNSS. "
            "NOT authoritative. Backend performs the authoritative map-match."
        ),
    )
    matched_road_segment_id: Optional[str] = Field(
        default=None,
        description="[BACKEND-OWNED] Authoritative road segment from backend map-match.",
    )
    map_match_confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="[BACKEND-OWNED] Backend map-match confidence.",
    )
    map_match_status: MapMatchStatus = Field(
        default=MapMatchStatus.PENDING,
        description="[BACKEND-OWNED] Backend map-match result status.",
    )

    # --- Event classification ---
    event_type: str = Field(
        description="Semantic type of event (e.g. 'pothole_observation', 'road_crack_observation')."
    )

    # --- Cross-references ---
    observation_id: Optional[str] = Field(
        default=None,
        description="Reference to the Observation that produced this event.",
    )
    opportunity_id: Optional[str] = Field(
        default=None,
        description="Reference to the ObservationOpportunity associated with this event.",
    )
    evidence_ref: Optional[str] = Field(
        default=None,
        description="Reference to evidence artifact (MinIO/GCS key). Optional.",
    )
    track_id: Optional[str] = Field(
        default=None,
        description="Multi-frame track identifier from Edge tracker. Optional.",
    )
    telemetry_speed_kmh: Optional[float] = Field(
        default=None,
        description="Explicit vehicle telemetry / CAN-bus speed in km/h if available. Optional.",
    )

    # --- Quality dimensions (DISTINCT — never merge into one "confidence") ---
    detector_confidence: float = Field(
        ge=0.0,
        le=1.0,
        description=(
            "Raw detector model confidence. "
            "NOT evidence confidence, NOT RoadTwin confidence."
        ),
    )
    observation_quality: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Overall observation quality derived from Opportunity scores.",
    )
    gps_quality: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="GPS fix quality at event time.",
    )

    # --- Model provenance ---
    model_name: str = Field(description="Detector model that produced the observation.")
    model_version: str = Field(description="Detector model version.")

    # --- Routing/tracing ---
    priority: EventPriority = Field(
        default=EventPriority.P2,
        description="MQTT routing priority.",
    )
    trace_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Distributed trace identifier.",
    )
    producer_sequence: int = Field(
        default=0,
        description="Monotonically increasing sequence number from Edge producer.",
    )
    payload_hash: Optional[str] = Field(
        default=None,
        description="SHA-256 of the canonical payload for integrity verification.",
    )

    model_config = ConfigDict()
